Fix shapeless tests by using a -> object instead of a function
Apparently shapeless completely messes up the function -> poly
conversion, for example:
scala> def inc(i: Int) = i + 1
inc: (i: Int)Int

scala> everywhere(inc _)(List(1,2,3))
res7: List[Int] = List(2, 3, 4)

scala> everywhere(inc _)(List(1,2,3))
java.lang.AbstractMethodError: fresh$macro$6$2$.caseUniv()Lshapeless/PolyDefns$Case;
... 43 elided

In this case, it just failed to update some salaries during
scalatest runs.

This fixes #3